### PR TITLE
Fix typo at student-hall-of-fame/index.html

### PR DESCRIPTION
**Pull request by ManosMagnus**

### CODE REVIEW

**Comment by thc202** [comment]
Thanks!

**Comment by thc202** [comment]
Note that it should also be applied in [zaproxy-website](https://github.com/zaproxy/zaproxy-website) repo.

**Comment by ManosMagnus** [comment]
No problem. Thank you for the mention :))
Didn't get the structure of the website tbh, why it should be changed in two places?

**Comment by thc202** [comment]
It should be just changed in the other repo, but this one is still not being updated automatically.

**Pull request merged**
